# Generated by Django 4.1.7 on 2023-03-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_bookingdate_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='id',
            new_name='ID',
        ),
    ]
