# Generated by Django 4.1.7 on 2023-03-31 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_booking_id_alter_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDate',
            new_name='BookingDateTime',
        ),
    ]
