# Generated by Django 4.1.7 on 2023-03-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_bookingdate_booking_bookingdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDateTime',
            new_name='BookingDate',
        ),
    ]
